// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace Blazor.Shared.Models
{
    public partial class BikeFrame : IBikeComponent, IRotorRelatedComponent, IShockBushingSizes, ISteererTubeRelatedComponent
    {
        public const string Codename = "bike_frame";
        public const string WheelSizeCodename = "wheel_size";
        public const string RotorRelatedComponentMinimumRotorDiameterMmCodename = "rotor_related_component__minimum_rotor_diameter__mm_";
        public const string RearDerailleurMountingTypeCodename = "rear_derailleur_mounting_type";
        public const string BrakeMountingTypeCodename = "brake_mounting_type";
        public const string BikeComponentWeightGramsCodename = "bike_component__weight__grams_";
        public const string BikeComponentImagesCodename = "bike_component__images";
        public const string RotorRelatedComponentMaximumRotorDiameterMmCodename = "rotor_related_component__maximum_rotor_diameter__mm_";
        public const string ShockRelatedComponentShockSizesEyeToEyeSizeStrokeSizeCodename = "shock_related_component__shock_sizes__eye_to_eye_size__stroke_size_";
        public const string BikeComponentNameCodename = "bike_component__name";
        public const string BikeComponentBikeKindCodename = "bike_component__bike_kind";
        public const string FrontDerailleurMountingTypeCodename = "front_derailleur_mounting_type";
        public const string SteererTubeRelatedComponentSteererTubeTypeCodename = "steerer_tube_related_component__steerer_tube_type";
        public const string BottomBracketTypeCodename = "bottom_bracket_type";
        public const string SteererTubeRelatedComponentSteererTubeDiameterCodename = "steerer_tube_related_component__steerer_tube_diameter";
        public const string ShockRelatedComponentShockHardwareSizesCodename = "shock_related_component__shock_bushing_sizes";
        public const string BikeComponentShortDescriptionCodename = "bike_component__short_description";
        public const string SuspensionTravelCodename = "suspension_travel";
        public const string BikeComponentLongDescriptionCodename = "bike_component__long_description";
        public const string SeatpostTubeDiameterCodename = "seatpost_tube_diameter";
        public const string MaterialSubstanceCodename = "material__substance_";

        #region "IBikeComponent members"

        [JsonProperty("bike_component__name")]
        public string Name { get; set; }

        [JsonProperty("bike_component__bike_kind")]
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }

        [JsonProperty("bike_component__short_description")]
        public string ShortDescription { get; set; }

        [JsonProperty("bike_component__long_description")]
        public IRichTextContent LongDescription { get; set; }

        [JsonProperty("bike_component__images")]
        public IEnumerable<Asset> Images { get; set; }

        [JsonProperty("bike_component__weight__grams")]
        public decimal? WeightGrams { get; set; }

        #endregion

        #region "IRotorRelatedComponent"

        [JsonProperty("rotor_related_component__minimum_rotor_diameter__mm_")]
        public decimal? MinimumRotorDiameterMm { get; set; }

        [JsonProperty("rotor_related_component__maximum_rotor_diameter__mm_")]
        public decimal? MaximumRotorDiameterMm { get; set; }

        #endregion

        #region "IShockRelatedComponent members"

        [JsonProperty("shock_related_component__shock_sizes__eye_to_eye_size__stroke_size_")]
        public IEnumerable<TaxonomyTerm> ShockSize { get; set; }

        [JsonProperty("shock_related_component__shock_bushing_sizes")]
        public IEnumerable<TaxonomyTerm> ShockBushingSizes { get; set; }

        #endregion

        #region "ISteererTubeRelatedComponent"

        [JsonProperty("steerer_tube_related_component__steerer_tube_type")]
        public IEnumerable<TaxonomyTerm> SteererTubeType { get; set; }

        [JsonProperty("steerer_tube_related_component__steerer_tube_diameter")]
        public IEnumerable<TaxonomyTerm> SteererTubeDiameter { get; set; }

        #endregion

        [JsonProperty("front_derailleur_mounting_type")]
        public IEnumerable<TaxonomyTerm> FrontDerailleurMountingType { get; set; }

        [JsonProperty("rear_derailleur_mounting_type")]
        public IEnumerable<TaxonomyTerm> RearDerailleurMountingType { get; set; }

        [JsonProperty("bottom_bracket_type")]
        public IEnumerable<TaxonomyTerm> BottomBracketType { get; set; }

        [JsonProperty("brake_mouting_type")]
        public IEnumerable<TaxonomyTerm> BrakeMountingType { get; set; }

        [JsonProperty("seatpost_tube_diameter")]
        public IEnumerable<TaxonomyTerm> SeatpostTubeDiameter { get; set; }

        [JsonProperty("wheel_size")]
        public IEnumerable<TaxonomyTerm> WheelSize { get; set; }

        [JsonProperty("material__substance_")]
        public IEnumerable<TaxonomyTerm> MaterialSubstance { get; set; }

        [JsonProperty("suspension_travel")]
        public IEnumerable<TaxonomyTerm> SuspensionTravel { get; set; }

        public ContentItemSystemAttributes System { get; set; }
    }
}