// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace Blazor.Shared.Models
{
    public partial class ConventionalBike
    {
        public const string Codename = "conventional_bike";
        public const string BikeSaddleCodename = "bike__saddle";
        public const string BikeHandlebarCodename = "bike__handlebar";
        public const string BikeTiresCodename = "bike__tires";
        public const string BikeCranksetCodename = "bike__crankset";
        public const string BikeFrontDerailleurCodename = "bike__front_derailleur";
        public const string BikeStemCodename = "bike__stem";
        public const string BikeFrontBrakeRotorCodename = "bike__front_brake_rotor";
        public const string BikeLongDescriptionCodename = "bike__long_description";
        public const string BikeSeatpostCodename = "bike__seatpost";
        public const string BikeRearBrakeRotorCodename = "bike__rear_brake_rotor";
        public const string BikeWheelsetCodename = "bike__wheelset";
        public const string BikeBikeKindCodename = "bike__bike_kind";
        public const string BikeImagesCodename = "bike__images";
        public const string BikeBrakesCodename = "bike__brakes";
        public const string BikeRearDerailleurCodename = "bike__rear_derailleur";
        public const string BikeShortDescriptionCodename = "bike__short_description";
        public const string BikeForkCodename = "bike__fork";
        public const string BikeFrameCodename = "bike__frame";
        public const string BikeShockCodename = "bike__shock";
        public const string BikeNameCodename = "bike__name";

        #region "IBike members"

        [JsonProperty("bike__name")]
        public string Name { get; set; }

        [JsonProperty("bike__bike_kind")]
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }

        [JsonProperty("bike__short_description")]
        public string ShortDescription { get; set; }

        [JsonProperty("bike__long_description")]
        public IRichTextContent LongDescription { get; set; }

        [JsonProperty("bike__frame")]
        public IEnumerable<object> Frame { get; set; }

        [JsonProperty("bike__fork")]
        public IEnumerable<object> Fork { get; set; }

        [JsonProperty("bike__wheelset")]
        public IEnumerable<object> Wheelset { get; set; }

        [JsonProperty("bike__brakes")]
        public IEnumerable<object> Brakes { get; set; }

        [JsonProperty("bike__front_brake_rotor")]
        public IEnumerable<object> FrontBrakeRotor { get; set; }

        [JsonProperty("bike__rear_brake_rotor")]
        public IEnumerable<object> RearBrakeRotor { get; set; }

        [JsonProperty("bike__crankset")]
        public IEnumerable<object> Crankset { get; set; }

        [JsonProperty("bike__seatpost")]
        public IEnumerable<object> Seatpost { get; set; }

        [JsonProperty("bike__shock")]
        public IEnumerable<object> Shock { get; set; }

        [JsonProperty("bike__stem")]
        public IEnumerable<object> Stem { get; set; }

        [JsonProperty("bike__handlebar")]
        public IEnumerable<object> Handlebar { get; set; }

        [JsonProperty("bike__saddle")]
        public IEnumerable<object> Saddle { get; set; }

        [JsonProperty("bike__tires")]
        public IEnumerable<object> Tires { get; set; }

        [JsonProperty("bike__front_derailleur")]
        public IEnumerable<object> FrontDerailleur { get; set; }

        [JsonProperty("bike__rear_derailleur")]
        public IEnumerable<object> RearDerailleur { get; set; }

        [JsonProperty("bike__images")]
        public IEnumerable<Asset> Images { get; set; }
        
        #endregion

        public ContentItemSystemAttributes System { get; set; }
    }
}