// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace Blazor.Shared.Models
{
    public partial class ElectricBike
    {
        public const string Codename = "electric_bike";
        public const string BikeSaddleCodename = "bike__saddle";
        public const string BikeHandlebarCodename = "bike__handlebar";
        public const string BikeTiresCodename = "bike__tires";
        public const string BikeCranksetCodename = "bike__crankset";
        public const string BikeFrontDerailleurCodename = "bike__front_derailleur";
        public const string BikeStemCodename = "bike__stem";
        public const string BikeFrontBrakeRotorCodename = "bike__front_brake_rotor";
        public const string BikeLongDescriptionCodename = "bike__long_description";
        public const string BikeKindCodename = "bike_kind";
        public const string BikeSeatpostCodename = "bike__seatpost";
        public const string RechargeTimeMinutesCodename = "recharge_time__minutes_";
        public const string BikeRearBrakeRotorCodename = "bike__rear_brake_rotor";
        public const string BikeWheelsetCodename = "bike__wheelset";
        public const string BikeBikeKindCodename = "bike__bike_kind";
        public const string BikeImagesCodename = "bike__images";
        public const string BikeBrakesCodename = "bike__brakes";
        public const string BikeRearDerailleurCodename = "bike__rear_derailleur";
        public const string BikeShortDescriptionCodename = "bike__short_description";
        public const string RangeKmCodename = "range__km_";
        public const string BikeForkCodename = "bike__fork";
        public const string BikeFrameCodename = "bike__frame";
        public const string BikeShockCodename = "bike__shock";
        public const string BikeNameCodename = "bike__name";

        public IEnumerable<object> BikeSaddle { get; set; }
        public IEnumerable<object> BikeHandlebar { get; set; }
        public IEnumerable<object> BikeTires { get; set; }
        public IEnumerable<object> BikeCrankset { get; set; }
        public IEnumerable<object> BikeFrontDerailleur { get; set; }
        public IEnumerable<object> BikeStem { get; set; }
        public IEnumerable<object> BikeFrontBrakeRotor { get; set; }
        public IRichTextContent BikeLongDescription { get; set; }
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }
        public IEnumerable<object> BikeSeatpost { get; set; }
        public decimal? RechargeTimeMinutes { get; set; }
        public IEnumerable<object> BikeRearBrakeRotor { get; set; }
        public IEnumerable<object> BikeWheelset { get; set; }
        public IEnumerable<TaxonomyTerm> BikeBikeKind { get; set; }
        public IEnumerable<Asset> BikeImages { get; set; }
        public IEnumerable<object> BikeBrakes { get; set; }
        public IEnumerable<object> BikeRearDerailleur { get; set; }
        public string BikeShortDescription { get; set; }
        public decimal? RangeKm { get; set; }
        public IEnumerable<object> BikeFork { get; set; }
        public IEnumerable<object> BikeFrame { get; set; }
        public IEnumerable<object> BikeShock { get; set; }
        public string BikeName { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}