// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace Blazor.Shared.Models
{
    public partial class Handlebar
    {
        public const string Codename = "handlebar";
        public const string BikeComponentWeightGramsCodename = "bike_component__weight__grams_";
        public const string BikeComponentImagesCodename = "bike_component__images";
        public const string BikeComponentNameCodename = "bike_component__name";
        public const string BikeComponentBikeKindCodename = "bike_component__bike_kind";
        public const string LengthMmCodename = "length__mm_";
        public const string BikeComponentShortDescriptionCodename = "bike_component__short_description";
        public const string BikeComponentLongDescriptionCodename = "bike_component__long_description";
        public const string HandlebarDiameterCodename = "handlebar_diameter";

        #region "IBikeComponent members"

        [JsonProperty("bike_component__name")]
        public string Name { get; set; }

        [JsonProperty("bike_component__bike_kind")]
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }

        [JsonProperty("bike_component__short_description")]
        public string ShortDescription { get; set; }

        [JsonProperty("bike_component__long_description")]
        public IRichTextContent LongDescription { get; set; }

        [JsonProperty("bike_component__images")]
        public IEnumerable<Asset> Images { get; set; }

        [JsonProperty("bike_component__weight__grams")]
        public decimal? WeightGrams { get; set; }

        #endregion

        [JsonProperty("handlebar_diameter")]
        public IEnumerable<TaxonomyTerm> HandlebarDiameter { get; set; }

        [JsonProperty("length__mm_")]
        public decimal? LengthMm { get; set; }

        public ContentItemSystemAttributes System { get; set; }
    }
}