// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace Blazor.Shared.Models
{
    public partial class Shock
    {
        public const string Codename = "shock";
        public const string BikeComponentWeightGramsCodename = "bike_component__weight__grams_";
        public const string BikeComponentImagesCodename = "bike_component__images";
        public const string ShockRelatedComponentShockSizesEyeToEyeSizeStrokeSizeCodename = "shock_related_component__shock_sizes__eye_to_eye_size__stroke_size_";
        public const string BikeComponentNameCodename = "bike_component__name";
        public const string BikeComponentBikeKindCodename = "bike_component__bike_kind";
        public const string ShockRelatedComponentShockHardwareSizesCodename = "shock_related_component__shock_bushing_sizes";
        public const string BikeComponentShortDescriptionCodename = "bike_component__short_description";
        public const string BikeComponentLongDescriptionCodename = "bike_component__long_description";

        #region "IBikeComponent members"

        [JsonProperty("bike_component__name")]
        public string Name { get; set; }

        [JsonProperty("bike_component__bike_kind")]
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }

        [JsonProperty("bike_component__short_description")]
        public string ShortDescription { get; set; }

        [JsonProperty("bike_component__long_description")]
        public IRichTextContent LongDescription { get; set; }

        [JsonProperty("bike_component__images")]
        public IEnumerable<Asset> Images { get; set; }

        [JsonProperty("bike_component__weight__grams")]
        public decimal? WeightGrams { get; set; }

        #endregion

        #region "IShockRelatedComponent members"

        [JsonProperty("shock_related_component__shock_sizes__eye_to_eye_size__stroke_size_")]
        public IEnumerable<TaxonomyTerm> ShockSize { get; set; }

        [JsonProperty("shock_related_component__shock_bushing_sizes")]
        public IEnumerable<TaxonomyTerm> ShockBushingSizes { get; set; }

        #endregion

        public ContentItemSystemAttributes System { get; set; }
    }
}