// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace Blazor.Shared.Models
{
    public partial class Stem
    {
        public const string Codename = "stem";
        public const string BikeComponentWeightGramsCodename = "bike_component__weight__grams_";
        public const string BikeComponentImagesCodename = "bike_component__images";
        public const string BikeComponentNameCodename = "bike_component__name";
        public const string BikeComponentBikeKindCodename = "bike_component__bike_kind";
        public const string SteererTubeRelatedComponentSteererTubeTypeCodename = "steerer_tube_related_component__steerer_tube_type";
        public const string SteererTubeRelatedComponentSteererTubeDiameterCodename = "steerer_tube_related_component__steerer_tube_diameter";
        public const string BikeComponentShortDescriptionCodename = "bike_component__short_description";
        public const string BikeComponentLongDescriptionCodename = "bike_component__long_description";

        #region "IBikeComponent members"

        [JsonProperty("bike_component__name")]
        public string Name { get; set; }

        [JsonProperty("bike_component__bike_kind")]
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }

        [JsonProperty("bike_component__short_description")]
        public string ShortDescription { get; set; }

        [JsonProperty("bike_component__long_description")]
        public IRichTextContent LongDescription { get; set; }

        [JsonProperty("bike_component__images")]
        public IEnumerable<Asset> Images { get; set; }

        [JsonProperty("bike_component__weight__grams")]
        public decimal? WeightGrams { get; set; }

        #endregion

        #region "ISteererTubeRelatedComponent"

        [JsonProperty("steerer_tube_related_component__steerer_tube_type")]
        public IEnumerable<TaxonomyTerm> SteererTubeType { get; set; }

        [JsonProperty("steerer_tube_related_component__steerer_tube_diameter")]
        public IEnumerable<TaxonomyTerm> SteererTubeDiameter { get; set; }

        #endregion

        public ContentItemSystemAttributes System { get; set; }
    }
}