// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;

using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace Blazor.Shared.Models
{
    public partial class Wheelset
    {
        public const string Codename = "wheelset";
        public const string RotorRelatedComponentMinimumRotorDiameterMmCodename = "rotor_related_component__minimum_rotor_diameter__mm_";
        public const string BikeComponentWeightGramsCodename = "bike_component__weight__grams_";
        public const string BrakeRotorMountingTypeCodename = "brake_rotor_mounting_type";
        public const string BikeComponentImagesCodename = "bike_component__images";
        public const string RotorRelatedComponentMaximumRotorDiameterMmCodename = "rotor_related_component__maximum_rotor_diameter__mm_";
        public const string WheelSizeCodename = "wheel_size";
        public const string TireRelatedComponentMinimumTireThicknessInchesCodename = "tire_related_component__minimum_tire_thickness__inches_";
        public const string BikeComponentNameCodename = "bike_component__name";
        public const string BikeComponentBikeKindCodename = "bike_component__bike_kind";
        public const string TireRelatedComponentMaximumTireThicknessInchesCodename = "tire_related_component__maximum_tire_thickness__inches_";
        public const string MaterialSubstanceCodename = "material__substance_";
        public const string BikeComponentShortDescriptionCodename = "bike_component__short_description";
        public const string BikeComponentLongDescriptionCodename = "bike_component__long_description";

        #region "IBikeComponent members"

        [JsonProperty("bike_component__name")]
        public string Name { get; set; }

        [JsonProperty("bike_component__bike_kind")]
        public IEnumerable<TaxonomyTerm> BikeKind { get; set; }

        [JsonProperty("bike_component__short_description")]
        public string ShortDescription { get; set; }

        [JsonProperty("bike_component__long_description")]
        public IRichTextContent LongDescription { get; set; }

        [JsonProperty("bike_component__images")]
        public IEnumerable<Asset> Images { get; set; }

        [JsonProperty("bike_component__weight__grams")]
        public decimal? WeightGrams { get; set; }

        #endregion

        #region "ITireRelatedComponent members"

        [JsonProperty("tire_related_component__minimum_tire_thickness__inches_")]
        public decimal? TireRelatedComponentMinimumTireThicknessInches { get; set; }

        [JsonProperty("tire_related_component__maximum_tire_thickness__inches_")]
        public decimal? TireRelatedComponentMaximumTireThicknessInches { get; set; }

        #endregion

        #region "IRotorRelatedComponent"

        [JsonProperty("rotor_related_component__minimum_rotor_diameter__mm_")]
        public decimal? MinimumRotorDiameterMm { get; set; }

        [JsonProperty("rotor_related_component__maximum_rotor_diameter__mm_")]
        public decimal? MaximumRotorDiameterMm { get; set; }

        #endregion

        [JsonProperty("material__substance_")]
        public IEnumerable<TaxonomyTerm> MaterialSubstance { get; set; }

        [JsonProperty("brake_rotor_mounting_type")]
        public IEnumerable<TaxonomyTerm> BrakeRotorMountingType { get; set; }

        [JsonProperty("wheel_size")]
        public IEnumerable<TaxonomyTerm> WheelSize { get; set; }

        public ContentItemSystemAttributes System { get; set; }
    }
}